- ts/twitter/src/app/error.tsx
- ts/twitter/src/app/profile/_components/my-profile.tsx
https://github.com/okuda-seminar/Twitter-Clone/issues/472
Added error.tsx file, which follows the official Next.js code conventions. Additionally, removed error rendering and useEffect from my-profile.tsx.
Please verify that `error.tsx` is rendered when fetch errors occur on the /profile route by testing different scenarios such as changing the endpoint or username.
https://github.com/user-attachments/assets/7e4856d9-f4d8-4e23-b5d8-4736305d0a65
I was unable to implement manual mocks properly, and therefore could not write the tests scheduled for this week.
2024/11/22
> [TS] Implement Loading and Error Pages for Data Fetching States

- .github/workflows/ts_test.yaml
#518 
Run yarn test when pushing changes to the ts directory.
- CI/CD
Please check if the workflow is triggered correctly.
Nothing added.
12/6
> [CI/CD] Run yarn test when pushing changes to the ts directory

- ts/twitter/src/app/@modal/(.)compose/post/__test__/post-modal.spec.tsx
- ts/twitter/src/app/home/__test__/home.spec.tsx
https://github.com/okuda-seminar/Twitter-Clone/issues/522
I corrected the grammar in the test description.
None
None
1/10
> [TS] Fix test descriptions in home.spec.tsx and post-modal.tsx

- ts/twitter/package.json
- ts/twitter/src/lib/sdk/rabbitmq-logger-sdk/_test_/rabbitmq-logger.test.ts
- ts/twitter/src/lib/sdk/rabbitmq-logger-sdk/rabbitmq-logger.ts
- ts/twitter/yarn.lock
#554 
- Developed an SDK that sends structured log messages to RabbitMQ.  
- Ensured each log contains `object_id`, `event_type`, and `created_at`.  
- Connection to RabbitMQ is established before sending a log and closed immediately afterward to reduce connection overhead.  
- Execution Timing: This SDK is executed whenever a log needs to be sent to RabbitMQ.  
- Value Changes: Log messages will now be queued in RabbitMQ instead of being stored or processed synchronously.  
- Ensure the SDK properly connects to RabbitMQ and handles connection.  
in local env
1st in log service (backend), set up rabbitmq.
```
make up
```
2nd in twitter-clone/ts/twitter
```
twitter git:(feature/#18_Implement_SDK_that_send_ctr_log) npm test                                                             
> …
```
> [TS] Implement SDK that send log to rabbitmq

- go/Makefile
- go/api/handlers/login_handler.go
- go/api/handlers/login_handler_test.go
- go/api/handlers/setup_test.go
- go/api/server.go
- go/api/transfers/to_login_response.go
- go/config/oapi_models_config.yml
- go/config/oapi_server_config.yml
- go/docker-compose.yaml
- go/internal/app/errors/errors.go
- go/internal/app/usecases/login_usecase.go
- go/internal/infrastructure/persistence/users_repository.go
- go/openapi/models.gen.go
- go/openapi/server.gen.go
- openapi/components/requests/login_request.yml
- openapi/components/responses/login_response.yml
- openapi/openapi.yml
- openapi/paths/login.yml
#588
Implement the login handler and usecase.
Mount `bundled-openapi.yml` inside the container."
- The correctness of the definition of the login handler and usecase.
- The correctness of the expected input and output.
Please run the following commands:
````
$ make exec_app
$ go test  -v ./...
`````
3/15
> [Go] Implement Login Handler and Usecase for User Authentication

- go/api/handlers/create_quote_repost_handler.go
- go/api/handlers/create_quote_repost_handler_test.go
- go/api/handlers/delete_repost_handler.go
- go/api/handlers/delete_repost_handler_test.go
- go/api/handlers/get_reverse_chronological_home_timeline_test.go
- go/api/handlers/handlers_test.go
- go/api/handlers/types.go
- go/api/server.go
- go/db/migrations/000010_update_reposts_table.down.sql
- go/db/migrations/000010_update_reposts_table.up.sql
- go/internal/domain/entities/repost.go
- go/internal/domain/entities/timelineEvent.go
- go/openapi/models.gen.go
- go/openapi/server.gen.go
- openapi/components/examples/get_reverse_chronological_home_timeline_example.yml
- openapi/components/requests/create_quote_repost_request.yml
- openapi/components/requests/delete_repost_request.yml
- openapi/components/responses/create_quote_repost_response.yml
- openapi/components/responses/create_repost_response.yml
- openapi/components/responses/get_reverse_chronological_home_timeline_response.yml
- openapi/openapi.yml
- openapi/paths/delete_reposts.yml
- openapi/paths/quote_reposts.yml
#569 
Updated the database schema to support the repost feature. Implemented the `createReposts` and `createQuoteReposts` and `DeleteReposts` handlers and added Reposts to the timeline entities. Updated the OpenAPI documentation accordingly.
- database schema
- `createReposts` and `createQuoteReposts` and `DeleteReposts`  handlers
- OpenAPI documentation
Please check the following three points:
- Whether the migration file is correct.
- Whether the handler implementations are correct.
- Whether the OpenAPI documentation is accurate.
`go test -v ./...`
handler test:
Verify that a notification appears in the timeline when creating a repost and a quote repost using the following command.
1. CreateUser
```
curl --location 'http://localhost:80/api/users' \
--header 'Content-Type: …
```
> [Go] Implement reposts using a naive approach

- go/db/migrations/000011_create_timelineitems_table.down.sql
- go/db/migrations/000011_create_timelineitems_table.up.sql
- go/docker/Dockerfile
- go/docker/app.Dockerfile
- go/go.mod
#604 
Upgrade the Go version to enable omitzero.
Modify the migration file to add the timelineitems table.
- DB table
- Go version
Please check whether the migration file is correct and if the Go version has been upgraded successfully.
Nothing added.
3/15
> [Go] Update go version and migration files

- swift/Twitter-iOS/Twitter-iOS.xcodeproj/project.pbxproj
- swift/Twitter-iOS/Twitter-iOS/Features/Home/HomeViewController.swift
- swift/Twitter-iOS/Twitter-iOS/Features/Post/Entities/PostModel.swift
- swift/Twitter-iOS/Twitter-iOS/Features/Post/NewPost/NewPostEditViewController.swift
- swift/Twitter-iOS/Twitter-iOS/Features/Post/RepostOptionsBottomSheet.swift
- swift/Twitter-iOS/Twitter-iOS/Features/Subscription/SubscribeOptionsViewController.swift
- swift/Twitter-iOS/Twitter-iOS/Features/User/UserProfile/UserBookmarksPageViewController.swift
- swift/Twitter-iOS/Twitter-iOS/Features/User/UserProfile/UserFollowerRequestsPageViewController.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Bookmark/BookmarkService.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Follow/FollowService.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Post/PostService.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Subscription/SubscriptionService.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Timeline/Entities/TimelineSSEDataModel.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Timeline/Entities/TimelineSSEPostModel.swift
- swift/Twitter-iOS/Twitter-iOS/Services/Timeline/TimelineService.swift
https://github.com/okuda-seminar/Twitter-Clone/issues/583
This PR introduces a service that fetches post-related data from the backend using Server-Sent Events (SSE). The app listens for updates to the timeline and processes events in real-time as users interact with the timeline view.
When users access the timeline view, the app establishes an SSE connection to receive live updates. The connection is active while the timeline view is visible. Once the timeline view disappears, the app terminates the SSE connection to stop receiving events.
I would appreciate your review, especially on the following two aspects:
- Setting the temporary ID
- Implement the SSE service code 
I’ve used an environment variable to set a temporary ID in order to avoid uploading actual user IDs to the internet. …
> [iOS] Implement Service Code to Fetch Data from Backend with SSE

- ts/twitter/src/app/login/_components/account-modal.tsx
- ts/twitter/src/app/login/_components/login-modal.tsx
- ts/twitter/src/app/login/_components/password-modal.tsx
- ts/twitter/src/app/login/_components/use-password-modal.ts
- ts/twitter/src/lib/actions/login.ts
- ts/twitter/src/lib/models/login-form-types.ts
- ts/twitter/src/lib/models/user.ts
- ts/twitter/src/lib/theme.ts
#608
Implement the login logic on the frontend.
If an already created account is used, login is possible. However, using user information to perform any actions is not yet implemented.
- Check if the login logic is correct. 
- Confirm that the following screen appears when attempting to login
Screen When Existing User Enters Correct Password To Login:
https://github.com/user-attachments/assets/ad3f5772-69e4-4abd-abb4-a3cd9353083f
Screen When Existing User Enters Incorrect Password To Login:
https://github.com/user-attachments/assets/19c2019a-7ec1-455d-883c-59c37fbe301a
Screen When Existing User Enters with network error:
https://github.com/user-attachments/assets/5ab4bcca-2087-481c-8d93-a3f759c378b6
Screen When Trying to Login with a Non-existent User To Login: …
> [TS] Implement the Login logic

- ts/twitter/.storybook/preview.tsx
- ts/twitter/package.json
- ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/post-modal.stories.ts
- ts/twitter/src/app/explore/_components/explore.stories.tsx
- ts/twitter/src/app/home/_components/timeline/timeline-feed.stories.tsx
- ts/twitter/src/app/layout.tsx
- ts/twitter/src/app/notifications/_components/notifications.stories.tsx
- ts/twitter/src/app/posts/[id]/_components/post-detail.stories.tsx
- ts/twitter/src/app/profile/_components/my-profile-tab.stories.tsx
- ts/twitter/src/lib/components/icon-button-with-link/icon-button-with-link.stories.tsx
- ts/twitter/src/lib/components/icon-button-with-link/icon-button-with-link.tsx
- ts/twitter/src/lib/components/mini-profile/mini-profile.tsx
- ts/twitter/src/lib/components/page-layout.tsx
- ts/twitter/src/lib/components/providers.tsx
- ts/twitter/src/lib/components/right-column/right-column.tsx
- ts/twitter/src/lib/components/sidebar-post-button/sidebar-post-button.tsx
- ts/twitter/src/lib/components/sidebar/sidebar.tsx
- ts/twitter/src/lib/components/sign-in-button.tsx
- ts/twitter/src/lib/components/ui/color-mode.tsx
- ts/twitter/src/lib/components/ui/provider.tsx
- ts/twitter/src/lib/components/ui/toaster.tsx
- ts/twitter/src/lib/components/ui/tooltip.tsx
- ts/twitter/src/lib/theme.ts
- ts/twitter/yarn.lock
https://github.com/okuda-seminar/Twitter-Clone/issues/607
I have updated the lib directory to be compatible with Chakra v3. The changes can be verified using Chromatic. For the storybook in the app directory, I have configured it to be excluded from the VRT
Please compare the stories before (v2) and after (v3) the update, and if there are no issues, please accept the UI changes.
I was unable to successfully change the color of the `IconButton`. If necessary, I will add a TODO comment. Please check this during your review.
3/21
> [TS] Update ChakraUI to v3 for UI components in lib directory

- ts/twitter/src/app/posts/[id]/_components/post-detail.stories.tsx
- ts/twitter/src/app/posts/[id]/_components/post-detail.tsx
- ts/twitter/src/app/profile/_components/my-profile-tab.stories.tsx
- ts/twitter/src/app/profile/_components/my-profile-tab.tsx
- ts/twitter/src/app/profile/_components/my-profile.tsx
https://github.com/okuda-seminar/Twitter-Clone/issues/625
I have updated the profile and posts directory to be compatible with Chakra v3. The changes can be verified using Chromatic. 
Please compare the stories before (v2) and after (v3) the update, and if there are no issues, please accept the UI changes.
3/28
> [TS] Update ChakraUI to v3 for UI components in posts and profile directory

- bff/biome.json
- bff/package.json
- bff/src/app.module.ts
- bff/src/schema.gql
- bff/src/timeline/inputs/create-post.input.ts
- bff/src/timeline/models/nullable-uuid.ts
- bff/src/timeline/models/post.model.ts
- bff/src/timeline/models/quote-repost.model.ts
- bff/src/timeline/models/repost.model.ts
- bff/src/timeline/models/timeline-item.model.ts
- bff/src/timeline/timeline.module.ts
- bff/src/timeline/timeline.resolver.ts
- bff/src/timeline/timeline.service.ts
- bff/yarn.lock
#686 
This pull request introduces the `CreatePost` mutation and `GetUserPosts` query to the BFF.
- Configured `GraphQLModule` following the [official documentation](https://docs.nestjs.com/graphql/quick-start).
- Set up `HttpModule` according to the [official documentation](https://docs.nestjs.com/techniques/http-module).
- Created models such as `post.model.ts`, `repost.model.ts`, `quote-repost.model.ts`, and `timeline-item.model.ts` to represent different post types and timeline items.
- Implemented the GraphQL resolver and its underlying service to handle communication with the backend.
- Generated the GraphQL schema based on the defined models.
- Enabled the `unsafeParameterDecoratorsEnabled` rule in Biome to allow decorating function parameters.
This change introduces new GraphQL …
> [BFF] Implement CreatePost and GetUserPosts

- terraform/.gitignore
- terraform/README.md
- terraform/environments/prd/backend.tf
- terraform/environments/prd/main.tf
- terraform/environments/prd/provider.tf
- terraform/environments/prd/terraform.tf
- terraform/environments/prd/variables.tf
- terraform/environments/prd/vars.tfvars.sample
- terraform/modules/s3/main.tf
- terraform/modules/s3/variables.tf
#693 
Setup an S3 bucket using Terraform.
- The execution occurs when you run terraform apply.
- The value that changes is the infrastructure—specifically, the creation of the S3 bucket in your AWS account.
- Unclear points in the README.md content
- Placement of the Terraform code, etc.
```
$ terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "aws_s3_bucket" "static" {
+ acceleration_status         = (known after apply)
+ acl                         = (known after apply)
+ arn                         = (known after apply)
+ bucket                      = "prd-x-clone"
+ bucket_domain_name          = (known after apply)
+ …
```
> [Infra] Implement an S3 bucket

- .github/workflows/terraform_code_quality.yaml
- terraform/.tflint.hcl
- terraform/modules/s3/variables.tf
#700 
I installed `TFLint` to detect it on terraform CI. In addition, I dealt with some existing code that could not be detected.
Affects all terraform code
None
There is no outputs.
```
$ tflint --recursive --config $PWD/.tflint.hcl
```
None
> [CI/CD] Add terraform CI

- go/cmd/main.go
- go/internal/application/usecase/interactor/update_notification.go
- go/internal/application/usecase/update_notification.go
- go/internal/controller/handler/create_post.go
- go/internal/controller/handler/create_quote_repost.go
- go/internal/controller/handler/create_repost.go
- go/internal/controller/handler/delete_repost.go
- go/internal/controller/handler/get_reverse_chronological_home_timeline.go
- go/internal/controller/handler/handlers.go
- go/internal/controller/server.go
- go/internal/domain/repository/users.go
- go/internal/infrastructure/fake/users.go
- go/internal/infrastructure/persistence/users.go
#705 
The updateNotification usecase is introduced. The post/delete handler will realize the update notification by calling the usecase, and the timeline side will call set and delete from the usecase to receive the update notification.
- Implement `UpdateNotificationUsecase` interface, and its interactor
- `createPost`, `CreateRepost`, `CreateQuoteRepost`, `DeleteRepost`, and `DeleteRepost` handlers use the `UpdateNotificationUsecase` to send the post/delete notification to the users accessing the timeline.
- Implement the `Followee` method in the users repository, which is used in the `updateNotificationUsecase` interactor.
Check if the implementation is appropriate.
Please test with the following commands.
- create user
```
curl -X POST http://localhost:80/api/users \
-H "Content-Type: …
```
> [Go] Introduce notification usecase

- cache/Dockerfile
- cache/docker-compose.yml
#711 
This PR is adding basic docker config files for Redis.
Added Redis is not used by GraphQL yet.
If Redis server is running after docker container starts and volume is working.
```sh
cd cache
docker compose up -d
docker compose exec redis sh
redis-cli
set mykey "Hello, Redis!"
get mykey
// "Hello, Redis!"
exit
docker compose down
docker compose up -d
docker compose exec redis sh
redis-cli
get mykey
// "Hello, Redis!"
```
Anytime.
> [BFF] Introduce Redis

- ts/twitter/src/lib/components/more-popup/more-popup.stories.tsx
- ts/twitter/src/lib/components/more-popup/more-popup.tsx
- ts/twitter/src/lib/components/sidebar/sidebar.tsx
#704 
- Add DropDown functionality for `More`
- Update sidebar display and UX.
Please check if the UI looks fine and if there are any violations of the TypeScript coding conventions.
None
5/3
> [TS] Add popup functionality to the More menu

- .github/workflows/format.yaml
- .github/workflows/go_test.yaml
- .github/workflows/k8s_policy.yaml
#707 
Skip Go and Kustomize tests if no related changes are detected, such as #709.
All PR
None
None
None
> [CI/CD] Skip Go and Kustomize tests if no related changes are detected

- ts/twitter/src/lib/actions/logout.ts
- ts/twitter/src/lib/actions/mocks/logout.mock.ts
- ts/twitter/src/lib/components/icons/index.ts
- ts/twitter/src/lib/components/icons/three-dots-icon.tsx
- ts/twitter/src/lib/components/mini-profile/mini-profile.tsx
#745
Currently, we don't have a logout function, requiring manual cookie clearing to reset the session. This is inconvenient, so I've implemented proper logout functionality on the frontend. The logout screen was implemented based on the official screenshot below.
Users can now logout to properly reset their session.
Verify the logout logic implementation is correct.
Verify the logout functionality works as demonstrated in the video.
https://github.com/user-attachments/assets/29133135-b53b-473e-b9f5-66cf9cd48272
6/7
> [TS] Implement logout on the frontend

- go/internal/application/usecase/api/users_and_followee_posts.go
- go/internal/application/usecase/fake/update_notification.go
- go/internal/application/usecase/fake/users_and_followee_posts.go
- go/internal/application/usecase/implementation/users_and_followee_posts.go
- go/internal/application/usecase/injector/users_and_followee_posts.go
- go/internal/controller/handler/errors.go
- go/internal/controller/handler/get_reverse_chronological_home_timeline.go
- go/internal/controller/handler/get_reverse_chronological_home_timeline_test.go
#785
This PR introduces a fake implementation of the `userAndFolloweePostsUsecase` and `updateNotificationUsecase` and adds a corresponding suite of unit tests.
GetReverseChronologicalHomeTimeline is tested with the fake `userAndFolloweePostsUsecase`and `updateNotificationUsecase`
Please verify that the test cases are sufficient.
07/26
> [Go] Write tests in getReverseChronologicalHomeTimelineHandler

- go/internal/application/usecase/api/get_post_by_post_id.go
- go/internal/application/usecase/implementation/get_post_by_post_id.go
- go/internal/application/usecase/injector/get_post_by_post_id.go
- go/internal/controller/handler/errors.go
- go/internal/controller/handler/get_post_by_post_id.go
- go/internal/controller/handler/get_post_by_post_id_test.go
- go/internal/controller/server.go
- go/internal/controller/transfer/to_get_post_by_post_id_response.go
- go/internal/controller/transfer/to_open_api_timeline_item.go
- go/internal/infrastructure/implementation/timeline_items.go
- go/internal/openapi/models.gen.go
- go/internal/openapi/server.gen.go
- openapi/components/responses/get_post_by_post_id_response.yml
- openapi/components/schemas/parent_post.yml
- openapi/components/schemas/post.yml
- openapi/components/schemas/quote_repost_with_parent.yml
- openapi/components/schemas/repost_with_parent.yml
- openapi/paths/posts_postId.yml
#810 
This PR introduces the getPostByPostID handler
- Implementation of the getPostByPostID handler
- Are test cases adequate?
- Is the openAPI definition adequate?
8/23
> [Go] Implement getPostByPostID

- ts/twitter/src/lib/components/right-column/components/premium-subscription-card.tsx
- ts/twitter/src/lib/components/right-column/components/trending-hashtags-list.tsx
- ts/twitter/src/lib/components/right-column/components/trending-news-list.tsx
- ts/twitter/src/lib/components/right-column/components/user-recommendation-list.tsx
- ts/twitter/src/lib/components/right-column/dummy/hashtags.ts
- ts/twitter/src/lib/components/right-column/dummy/news.ts
- ts/twitter/src/lib/components/right-column/dummy/users.ts
- ts/twitter/src/lib/components/right-column/right-column.tsx
https://github.com/okuda-seminar/Twitter-Clone/issues/815
Implemented the right-column UI using mock data
Please check if there are any issues with the right-column UI.
nothing added.
2025/8/29
> [TS] Add mock data to right-column and implement UI display

- ts/twitter/src/app/(protected)/@modal/(.)message/compose/_components/new-message-modal/new-message-modal.stories.tsx
- ts/twitter/src/app/(protected)/@modal/(.)message/compose/_components/new-message-modal/new-message-modal.tsx
- ts/twitter/src/app/(protected)/@modal/(.)message/compose/page.tsx
- ts/twitter/src/app/(protected)/message/_components/messages.tsx
- ts/twitter/src/app/(protected)/message/compose/page.tsx
- ts/twitter/src/lib/theme.ts
#804
A modal was implemented for writing a new message.
- Implement a modal
Please verify that the user interface (UI) renders correctly and that the TypeScript implementation complies with established coding conventions.
None
8/29
> [TS] Add Modal for New Message

- ts/twitter/src/app/(protected)/explore/_components/for-you.tsx
- ts/twitter/src/app/(protected)/explore/_components/search-tab-bar.tsx
- ts/twitter/src/app/(protected)/explore/_components/trending-hashtags-list.tsx
- ts/twitter/src/app/(protected)/explore/_components/trending-news-list.tsx
- ts/twitter/src/app/(protected)/explore/_components/user-recommendation-list.tsx
#834 
Same as title 
Storybook shows the diff.
9/27
> [TS] Add for you in explore tab
