okuda-seminar/Twitter-Clone

ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/use-post-modal.ts
ts/twitter/src/app/profile/_components/my-profile.tsx
ts/twitter/src/app/profile/page.tsx
ts/twitter/src/lib/actions/__test__/create-post.test.ts
ts/twitter/src/lib/actions/__test__/find-user-by-id.test.ts
ts/twitter/src/lib/actions/create-post.ts
ts/twitter/src/lib/actions/find-user-by-id.ts
ts/twitter/src/lib/actions/types.ts

#511 
This PR introduces the `Result` type as the return value for Server Actions. By returning a `Result` type instead of throwing errors, callers are required to handle errors explicitly, which enhances type safety, readability, and maintainability.  
According to [the Google TypeScript Style Guide](https://google.github.io/styleguide/tsguide.html#prefer-interfaces), interfaces are preferred over type aliases, so I used interfaces to define the related objects. However, since union types can only be defined using type aliases, the `ServerActionsResult` is implemented as a type alias.
- Server Actions
Please verify that the profile page is accessible and that you can create a post without any issues.
`@/lib/actions/__test__` has changed following the changes in Server Actions.
11/29

[TS] Introduce Result type for Server Actions

---

ts/twitter/src/app/home/__test__/home.spec.tsx
ts/twitter/src/app/notifications/__test__/notifications.spec.tsx
ts/twitter/src/app/notifications/_components/notifications-all-view.tsx
ts/twitter/src/app/notifications/_components/notifications-mentions-view.tsx
ts/twitter/src/app/notifications/_components/notifications-tab-bar.tsx
ts/twitter/src/app/notifications/_components/notifications-verified-view.tsx
ts/twitter/src/app/notifications/_components/notifications.tsx
ts/twitter/src/app/notifications/page.tsx
ts/twitter/src/lib/components/settings-button.tsx

https://github.com/okuda-seminar/Twitter-Clone/issues/517
I implemented the notifications page. It displays a page indicating there are no notifications.
The implementation for when notifications exist is not included in this PR.
https://github.com/user-attachments/assets/660a70e7-91e1-4ff6-b08f-e8604a633b53
`src/app/home/__test__/notifications.spec.tsx`
1. Start the frontend server (in the Twitter-Clone directory)
```
$ docker compose up -d
```
2. Enter the application container and run all test files
```
$ docker compose exec app bash
$ yarn test
```
　Use `--coverage` flag to generate coverage report
2024/12/6

[TS] Implement notifications UI at notifications page

---

swift/Twitter-iOS/Twitter-iOS/Features/Settings/Timeline/TimelineSettingsViewController.swift
swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionAnimator.swift
swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/509
This PR introduces a tap gesture recognizer to the dimming view (formerly defined as the overlay view), enabling the tap-to-dismiss functionality for the side menu.
When users tap the dimming view, the side menu will be dismissed.
Please check if the naming conventions in `DimmingView` are aligned with the intended functionalities.
https://github.com/user-attachments/assets/3d3785ae-d6ca-4447-86bd-0f8f802f3676
Until 12/7.

[iOS] Implement Tap Gesture on OverlayView to Dismiss Side Menu

---

swift/Twitter-iOS/Twitter-iOS/Features/Home/HomeViewController.swift
swift/Twitter-iOS/Twitter-iOS/Features/Settings/Timeline/TimelineSettingsViewController.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/523
This PR fixes a bug where the `UINavigationBar` was not appearing in the `TimelineSettingsViewController`. Now, the `UINavigationBar` is correctly displayed when the view is presented.
The `TimelineSettingsViewController` will now display with a `UINavigationBar` when users tap the settings button in the upper-right corner of the view.
Please review whether the way the `TimelineSettingsViewController` is presented is appropriate.
https://github.com/user-attachments/assets/c4755a6d-2381-45f2-a7a2-db9d4486fcf4
Until 12/14.

[iOS] Fix Bug Where UINavigationBar Does Not Appear in TimelineSettingsViewController

---

ts/twitter/src/app/@modal/(.)compose/post/__test__/post-modal.spec.tsx
ts/twitter/src/app/@modal/(.)compose/post/_components/post-button/post-button.tsx
ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/post-modal.tsx
ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/use-post-modal.ts
ts/twitter/src/lib/theme.ts

#477 
This PR displays an error message to users if post creation fails. To handle the result of post creation, I used the `useFormState` hook. This hook takes an action function as its first argument and the initial form state as its second argument.  
By using `useFormState`, we can easily manage form submissions via Server Actions. When a user clicks the post button, the current form state and form data are automatically passed to the action function—in this case, `handlePostButtonClick`. The action function then returns the next form state based on the result of the Server Actions.  
For example, we can return an error message to indicate the Server Actions has failed.
- This change affects the process of creating user posts.
Please check if you can see the following error message …

[TS] Display an error message to users if post creation fails

---

swift/Twitter-iOS/Twitter-iOS/Root/AppRootViewController.swift
swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionAnimator.swift
swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/510
This PR introduces a manual side menu transition controlled via a pan gesture.
Users can now open and close the side menu by dragging it with a pan gesture.
Please review if the way of introducing the `UIPercentDrivenInteractiveTransition` is appropriate.
https://github.com/user-attachments/assets/8018fa33-888e-473a-9b65-5aa0dbee1d29
Until 12/21.
- In `ScrollView`, users still can't open the side menu by gesture. This issue will be addressed in the https://github.com/okuda-seminar/Twitter-Clone/issues/531. 
- Although the issue and PR title mention a swipe gesture, the implementation uses only a pan gesture because it meets the required functionality without a swipe gesture for now.

[iOS] Implement Swipe and Pan Gesture to Enable Manual Side Menu Transition

---

swift/Twitter-iOS/Twitter-iOS/Root/MainRootViewController.swift
swift/Twitter-iOS/Twitter-iOS/Root/SideMenu/SideMenuTransitionController.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/531
This PR implements the side menu access via the pan gesture within a scroll view.
When users pan the view to the right within a scroll view, they can open the side menu. Additionally, when there is a horizontal scroll view, and users can still scroll the view to the right, they can scroll it rather than open the side menu. 
https://github.com/user-attachments/assets/16644024-6a90-416f-989a-b3bcf083c3ff
Until 12/28.
Besides the side menu access implementation, I added documentation comments to `MainRootViewController`.

[iOS] Enable Side Menu Access via Gesture Interaction within ScrollView

---

swift/Twitter-iOS/Twitter-iOS/Features/Jobs/JobsSearchTabView.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/343
This PR implements the example search queries displayed under the search bar in the `JobsSearchTabView`.
This view will appear when users tap the "Job" button in the side menu.
Please review if the approach used to define the default search queries (defaultSearchQueries) is appropriate.
https://github.com/user-attachments/assets/922a09f5-2976-4e0a-ae1f-2e0a353a674f
Until 1/4.

[iOS] Add example search queries UI under the search bar

---

ts/twitter/src/app/home/_components/timeline/__mocks__/post-data.ts
ts/twitter/src/app/home/_components/timeline/__test__/timeline-feed.spec.tsx
ts/twitter/src/app/home/_components/timeline/use-timeline-feed.ts

https://github.com/okuda-seminar/Twitter-Clone/issues/516
Added event types for EventSource messages to handle different SSE events. The system now processes post information updates based on the specific event type received.
Please verify that the timeline is displayed in the following tab. Currently, since the `follow` functionality has not been implemented yet, only your own posts will be displayed.
#Reference
https://github.com/user-attachments/assets/912ae43f-4d2a-468f-84bd-20d84c58e34a
`src/app/home/timeline/__test__/timeline-feed.spec.tsx`
1. Start the frontend server (in the Twitter-Clone directory)
```
$ docker compose up -d
```
2. Enter the application container and run all test files
```
$ docker compose exec app bash
$ yarn test
```
Please review using the latest version of …

[TS] Add event type handling for SSE timeline streaming

---

swift/Twitter-iOS/Podfile
swift/Twitter-iOS/Podfile.lock
swift/Twitter-iOS/Twitter-iOS.xcodeproj/project.pbxproj
swift/Twitter-iOS/Twitter-iOS.xcworkspace/contents.xcworkspacedata
swift/Twitter-iOS/Twitter-iOS/Features/Post/UserPostsCollectionViewCell.swift
swift/Twitter-iOS/Twitter-iOS/Features/User/UserProfile/UserProfileTabViewController.swift
swift/Twitter-iOS/Twitter-iOS/Features/User/UserProfile/UserProfileTabsViewController.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/547
This PR implements a new tabs view UI for integration with TwitterProfile OSS, which requires tracking the currently selected `UIViewController` in the user profile tabs view. To achieve this, I followed the example project from TwitterProfile OSS and integrated the XLPagerTabStrip library.
Users can switch between tabs by scrolling horizontally and view posts within each tab by scrolling vertically. You can check the views in the previews, not in the app for now.
Please check if the `UICollectionView` implementation is correct and whether the naming conventions and code style are appropriate.
Until 2/15.
- Preview of the newly created view.
https://github.com/user-attachments/assets/d73001f7-464e-4258-8085-8ff44ddd8c11
[Example …

[iOS] Create New Tabs View UI to Integrate with TwitterProfile OSS

---

ts/twitter/src/lib/sdk/rabbitmq-logger-sdk/_test_/rabbitmq-logger.test.ts
ts/twitter/src/lib/sdk/rabbitmq-logger-sdk/rabbitmq-logger.ts

#579 
Refactored RabbitMqLogger to include separate methods for sending tap logs and impression logs to improve modularity.
Refactor the sdk.
```
twitter git:(feature/#579_Refactor_the_ctr_log_sdk) ✗ yarn test
yarn run v1.22.22
$ jest
PASS  src/lib/actions/__test__/fetch-following-posts.test.ts
PASS  src/lib/sdk/rabbitmq-logger-sdk/_test_/rabbitmq-logger.test.ts
● Console
console.log
Log sent: {"eventType":"tap","objectId":"98765","createdAt":"2025-02-25T02:57:20.303Z"}
at RabbitMqLogger.log [as sendLogMessage] (src/lib/sdk/rabbitmq-logger-sdk/rabbitmq-logger.ts:46:15)
console.log
Log sent: {"eventType":"impression","objectId":"54321","createdAt":"2025-02-25T02:57:20.319Z"}
at RabbitMqLogger.log [as sendLogMessage] (src/lib/sdk/rabbitmq-logger-sdk/rabbitmq-logger.ts:46:15)
console.log
Log …
```

[TS] Implement a log-sending function for each event type

---

ts/twitter/src/app/home/_components/timeline/timeline-feed-service.ts
ts/twitter/src/lib/actions/__test__/create-post.test.ts
ts/twitter/src/lib/actions/__test__/find-user-by-id.test.ts
ts/twitter/src/lib/constants/error-messages.ts

https://github.com/okuda-seminar/Twitter-Clone/issues/489
The error messages were hard coded in the tests, so I moved them into ERROR_MESSAGE.
Please make sure the tests pass.
`ts/twitter/src/lib/actions/__test__/create-post.test.ts`
`ts/twitter/src/lib/actions/__test__/find-user-by-id.test.ts`
2/28

[TS] Centralize Error Messages Management

---

ts/twitter/src/app/login/_components/account-modal.tsx
ts/twitter/src/app/login/_components/login-modal.tsx
ts/twitter/src/app/login/_components/password-modal.tsx
ts/twitter/src/app/login/page.tsx

#598 
Implement login screen modals for auth task.
You can view 2 modals with login path.
- Check if the login directory structure is correct. 
- Verify that the following screen appears when accessing http://localhost:3000/login. 
- Confirm that clicking "next" displays the subsequent screen. 
- Ensure that clicking "login" redirects to the home path.
3/15

[TS] Implement login screen modals

---

go/internal/controller/handler/get_reverse_chronological_home_timeline.go
go/internal/controller/handler/get_reverse_chronological_home_timeline_test.go
go/internal/controller/handler/setup_test.go
go/internal/controller/server.go

#619 
Last Saturday, we discussed eliminating the environmental dependency by creating a new posting event when the event type is `InitialAccess`, but it did not work for the following reasons.
`httptest.NewRecorder()` writes the result received at the end of the handler's execution. `scanner.Scan()` requires the handler's function execution to have finished reading the response, and therefore, even if `the timelineEvent.EventType` causes a new post or other action, it will not be added to the recorder.
I added a channel to GetReverseChronologicalHomeTimelineHandler to tell it it is connected and to wait for this connection result when testing.
- `getReverseChronologicalHomeTimelineHandler` has a new member, named connected, which is used to tell the connection between client and server …

[Go] Fix the getReverseChronologicalHomeTimeline test

---

ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/post-modal.tsx

#622 
When Chromatic captures a screenshot of the "Error Form" test for "PostModal", the bottom-left icon sometimes receives focus (as seen in the right image). This caused the VRT to be flaky.
I fixed this issue by ensuring the text area gains focus not only when the modal is first opened but also after a submission failure.
- PostModal
Please verify that the text area gains focus after a submission failure.  
You can check it [[here](http://localhost:6006/?path=/story/features-postmodal--error-form)](http://localhost:6006/?path=/story/features-postmodal--error-form) after running `yarn storybook`.
Chromatic automatically runs VRT.
3/28

[TS] Fix the flaky test for PostModal

---

go/db/migrations/000012_update_posts_table.down.sql
go/db/migrations/000012_update_posts_table.up.sql
go/internal/application/usecase/interactor/specific_user_posts.go
go/internal/application/usecase/interactor/users_and_followee_posts.go
go/internal/application/usecase/specific_user_posts.go
go/internal/application/usecase/users_and_followee_posts.go
go/internal/controller/handler/create_post.go
go/internal/controller/handler/create_post_test.go
go/internal/controller/handler/create_quote_repost.go
go/internal/controller/handler/create_quote_repost_test.go
go/internal/controller/handler/create_repost.go
go/internal/controller/handler/create_repost_test.go
go/internal/controller/handler/delete_repost.go
go/internal/controller/handler/delete_repost_test.go
go/internal/controller/handler/get_user_posts_timeline.go
go/internal/controller/handler/get_user_posts_timeline_test.go
go/internal/controller/handler/setup_test.go
go/internal/domain/entity/timelineitem.go
go/internal/domain/repository/timelineitems.go
go/internal/domain/value/timeline_event.go
go/internal/infrastructure/persistence/timelineitems.go
go/internal/lib/featureflag/timeline.go
go/internal/lib/featureflag/timeline_test.go
openapi/components/responses/create_post_response.yml
openapi/components/responses/create_quote_repost_response.yml
openapi/components/responses/create_repost_response.yml
openapi/components/responses/get_user_posts_timeline_response.yml
openapi/paths/user_posts.yml

#572 
Update the database schema to manage posts, reposts, and quote reposts in a single table. Implement handlers other than `get_reverse_chronological_home_timeline` to align with the schema changes. The `get_reverse_chronological_home_timeline` handler will be implemented later. Use a feature flag to separate the processing for the old and new schemas.
- database schema
- `CreatePost`, `CreateRepost`, `CreateQuoteRepost`, `DeleteRepost`, `GetUserPostsTimeline`
handlers and tests
- usecase related to GetUserPostsTimeline
Please check whether each handler is implemented to support the new schema.
`go test -v ./...`
03/22

[Go] Implement reposts using the selected approach

---

swift/Twitter-iOS/Twitter-iOS.xcodeproj/project.pbxproj
swift/Twitter-iOS/Twitter-iOS/Features/Home/HomeTabView.swift
swift/Twitter-iOS/Twitter-iOS/Features/Home/HomeViewController.swift
swift/Twitter-iOS/Twitter-iOS/Features/Home/TimelinePostsDataSource.swift
swift/Twitter-iOS/Twitter-iOS/Services/Timeline/TimelineService.swift

https://github.com/okuda-seminar/Twitter-Clone/issues/584
This PR implements real-time UI updates for fetched posts using the timeline Server-sent events (SSE) connection. This enables users to view their posts in the "Following" tab within `HomeViewController`.
Users will now see posts fetched from the server in the Following tab of HomeViewController. Additionally, when a new post is created, it will automatically appear at the top of the "Following" tab.
Please review whether the post updating logic and error handling logic are appropriate.
https://github.com/user-attachments/assets/5a8f63cb-9392-4cb3-a6e4-3c84c0d3712a
Until 3/22.

[iOS] Implement Real Time UI Updates for Fetched Posts with SSE

---

go/internal/application/usecase/errors.go
go/internal/application/usecase/interactor/create_user.go
go/internal/controller/handler/create_user.go
go/internal/domain/repository/errors.go
go/internal/domain/repository/users.go
go/internal/infrastructure/fake/users.go
go/internal/infrastructure/fake/users_test.go
go/internal/infrastructure/persistence/users.go

#629 
This PR introduces `fakeUsersRepository`, a fake implementation of `UsersRepository`, and implements the `CreateUser` method for it. Instead of using a real database, it stores records in a map to simulate the behavior of the actual implementation.  
To allow controlled behavior, it includes a `createUserError` field, enabling callers to set an error that `CreateUser` will return.  
Since `fakeUsersRepository` has not yet been fully implemented, `NewUsersRepository` currently always returns the real implementation. The remaining functionality will be implemented in a future task.
- `fakeUsersRepository` is used in the test environment to mimic the real implementation.
Please check if the fake implementation and the way to control behavior are appropriate.
- …

[Go] Implement CreateUser method for fake UsersRepository

---

go/README.md

#649 
This PR adds the README with detailed OpenAPI documentation to help developers define, bundle, and implement new APIs in the Twitter-Clone project.  
The documentation covers:  
- Why we use OpenAPI in the project.  
- Steps to add a new API.  
- Guidelines for implementing an API.  
- Instructions for viewing the API documentation in a browser.  
Since the current process is cumbersome, I plan to introduce a pipeline that automatically uploads the [Swagger](https://swagger.io/) documentation to GitHub Pages whenever the OpenAPI schema is updated.
- documentation
Please review the updated documentation to ensure it provides sufficient information for developers.
Just documentation.
4/4

[Go] Add an OpenAPI section to the README

---

ts/twitter/package.json
ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/post-modal.stories.ts
ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/use-post-modal.ts
ts/twitter/src/app/login/_components/login-modal.tsx
ts/twitter/src/app/login/_components/password-modal.tsx
ts/twitter/src/app/signup/_components/signup-modal.stories.tsx
ts/twitter/src/app/signup/_components/signup-modal.tsx
ts/twitter/src/app/signup/_components/use-signup-modal.ts
ts/twitter/src/app/signup/page.tsx
ts/twitter/src/lib/actions/mocks/create-post.mock.ts
ts/twitter/src/lib/actions/mocks/signup.mock.ts
ts/twitter/src/lib/actions/signup.ts
ts/twitter/src/lib/constants/error-messages.ts
ts/twitter/src/lib/constants/validation-constants.ts
ts/twitter/src/lib/models/login-form-types.ts

#638 
Implement a signup modal screen for auth task.
You can view a signup modal with signup path, and you can create user with this modal.
Check if the signup directory structure is correct.
Please confirm that the behaviors matches the video below when accessing http://localhost:3000/signup.
https://github.com/user-attachments/assets/810e6c22-c01e-41e2-9a9b-d39b6047edf1
4/5

[TS] Implement a Sign Up Modal Screen

---

go/internal/domain/repository/errors.go
go/internal/domain/repository/timelineitems.go
go/internal/infrastructure/fake/timelineitems.go
go/internal/infrastructure/persistence/timelineitems.go

#668 
This PR introduces `fakeTimelineItemsRepository`, a fake implementation of `TimelineItemsRepository`, and I added the following method.
- CreatePost(userID, text string) (entity.TimelineItem, error)
- DeletePost(postID string) error
- CreateRepost(userID, postID string) (entity.TimelineItem, error)
- DeleteRepost(postID string) error
- CreateQuoteRepost(userID, postID, text string) (entity.TimelineItem, error)
- SetError(key string, err error)
- ClearError(key string)
These methods are implemented as the skeleton functionality necessary to avoid errors in the `timelineItemsRepository` while simulating repository interactions for testing and development purposes.
Methods have been added with the fake implementation, but there is no existing code that uses them. These methods will be …

[Go] Implement fake timelineitems repository

---

go/cmd/main.go
go/internal/controller/handler/create_followship.go
go/internal/controller/server.go
go/internal/openapi/models.gen.go
go/internal/openapi/server.gen.go
openapi/components/requests/create_followship_request.yml
openapi/components/responses/create_followship_response.yml
openapi/openapi.yml
openapi/paths/followship.yml

#676 
- This pull request implements the CreateFollowship handler.
- Separation of the handler (create_followship.go) for better test isolation
- Addition of the OpenAPI path definition (paths/followship.yml)
- Addition of request/response schema:
- components/requests/create_followship_request.yml
- components/responses/create_followship_response.yml
- Update to openapi.yml to register the new endpoint
This will be executed when a user sends a POST /api/users/{id}/follow request with a valid JSON payload (target_user_id).
- Make sure the request/response structure in OpenAPI aligns with the actual handler logic
- No regression is introduced to the existing server.go or handler registration
- The new endpoint doesn’t conflict with existing user-related endpoints
- OpenAPI bundling and …

[Go] Write createfollowship openapi to separate handler for test isolation

---

bff/src/schema.gql
bff/src/timeline/inputs/create-repost.input.ts
bff/src/timeline/timeline.resolver.ts
bff/src/timeline/timeline.service.ts

#691 
This pull request introduces the `CreateRepost` mutation.
- Implemented the GraphQL resolver and its underlying service to handle communication with the backend.
This change introduces new GraphQL operations:
- `CreateRepost(userId: string, input: CreateRepostInput): Repost` — Mutation for creating a new repost.
Please verify that the query and mutation execute correctly by following these steps:
1. Install dependencies:
```sh
yarn
```
2. Start the NestJS server:
```sh
yarn start
```
3. Start the backend server (in the `go` directory):
```sh
make start
make exec-app
go run ./cmd
```
4. Open Apollo Sandbox at [http://localhost:8080/graphql](http://localhost:8080/graphql).
5. Execute the query and mutation. You can set the request parameters in the **Variables** section.
**GraphQL …

[BFF] Implement CreateRepost

---

terraform/README.md
terraform/environments/prd/main.tf
terraform/modules/cognito/main.tf
terraform/modules/ec2/main.tf
terraform/modules/vpc/main.tf
terraform/modules/vpc/outputs.tf

#699 
This PR enables SSH access to the backend EC2 instance by introducing an Internet Gateway and configuring the route table.
Additionally, `user_data` has been added to allow the EC2 instance to automatically clone the Twitter-Clone repository and run the backend using Docker Compose.
This setup is executed when you run terraform apply.
If the network setup is appropriate.
1. Execute the Terraform actions
```
cd terraform/environments/prd
terraform init
terraform apply -var-file=vars.tfvars
```
2. Open the AWS console and connect to the instance.
3. Run the app
```sh
docker exec -it x_app go run ./cmd/main.go
```
4. Check if the app runs properly by sending a POST request.
```
curl --location 'http://{The IP address of your instance}:80/api/users' \
--header 'Content-Type: …
```

[Infra] Enable SSH access to EC2 and verify successful instance setup

---

terraform/environments/prd/main.tf
terraform/environments/prd/variables.tf
terraform/environments/prd/vars.tfvars.sample
terraform/modules/cognito/main.tf
terraform/modules/cognito/variables.tf
terraform/modules/s3/outputs.tf

#710 
Enabled access control where only users authenticated through Cognito and the Identity Pool can access the S3 bucket.
- Created a User Pool and User Pool Client supporting OAuth 2.0 Authorization Code Flow.
- Configured an Identity Pool to issue temporary AWS credentials to logged-in users.
- Set up IAM roles and policies to restrict S3 access to authenticated users only.
Changes apply only when deploying or destroying the Cognito authentication infrastructure using Terraform.
Affects creation and deletion of Cognito User Pool, User Pool Client, Identity Pool, IAM Roles, and their permissions related to S3 access.
Confirm that users authenticated via Cognito Hosted UI can successfully obtain temporary AWS credentials.
Confirm that authenticated users can list and get objects from …

[Infra] Add userpool that permit user to access S3

---

go/internal/controller/handler/create_followshiop_test.go
go/internal/controller/handler/create_followship.go
go/internal/controller/handler/errors.go
go/internal/controller/handler/handlers.go
go/internal/controller/handler/types.go
go/internal/controller/server.go

#690 
Changed NewCreateFollowshipHandler to accept a repository.UsersRepository instead of a raw *sql.DB.
Replaced the old handler.NewCreateFollowshipHandler(db) call with handler.NewCreateFollowshipHandler(infrastructure.InjectUsersRepository(db)) to switch between test and normal situations.
Covered three cases: successful creation, invalid JSON, and use-case error.
- Endpoint affected: POST /api/users/{id}/following
- Handler construction: now uses injected repository rather than direct DB access
- Modified handler works properly
- Test works individually
- handler test
success
failure(internal server error)
failure(bad request body)
- fake handler test
command
```
go test -v ./internal/controller/handler
```
result
```
➜  go git:(feature/#690_Refactor_createfollowship_test) go test -v …
```

[Go] Add CreateFollowship handler test that satisfies test isolation

---

ts/twitter/src/app/@modal/(.)compose/post/_components/post-modal/use-post-modal.ts
ts/twitter/src/lib/actions/__test__/create-post.test.ts
ts/twitter/src/lib/actions/create-post.ts

#737 
We are currently experiencing an issue where we cannot create posts from the frontend. When attempting to do so, the response status is 404, and the error message is as follows.
After investigation, I've determined that the issue stems from a mismatch between the endpoint URL used in the frontend and the actual endpoint implemented on the backend. This problem appears to have been introduced by a [PR](https://github.com/okuda-seminar/Twitter-Clone/pull/736/files#diff-98407184f9f853cb5b36a5dc6a0f563a1b8acd5f25cc18d20682334451f355b3) that changed the backend endpoint from `m.HandleFunc("POST "+options.BaseURL+"/api/posts", wrapper.CreatePost)` to `m.HandleFunc("POST "+options.BaseURL+"/users/{id}/posts", wrapper.CreatePost)`. However, the frontend server action is still using …

[TS] Fix API Endpoint Mismatch Preventing POST Creation

---

go/cmd/main.go
go/internal/controller/handler/delete_followship.go
go/internal/controller/handler/delete_followship_test.go
go/internal/controller/handler/errors.go
go/internal/controller/handler/handlers.go
go/internal/controller/server.go
go/internal/openapi/models.gen.go
go/internal/openapi/server.gen.go
openapi/components/responses/delete_followship_response.yml
openapi/openapi.yml
openapi/paths/delete_followship.yml

#735
This pull request adds unit tests for the DeleteFollowship handler.
* Introduced tests in `handler_test.go` using a fake `UsersRepository`.
* Covered the following cases:
* Successful deletion (expect HTTP 204)
* Followship not found (expect HTTP 404)
* Use-case error (expect HTTP 500)
I followed the Twitter API v2 documentation.[twitter api doc v2 ](https://apidog.com/apidoc/docs-site/345999/api-3514022)
These tests run when executing `go test` and validate the DeleteFollowship endpoint’s behavior. No changes are made to production code or handler registration.
* The fake repository simulates `UnfollowUser` correctly.
* Assertions for HTTP status codes match the expected behavior.
* No unintended side-effects on other handler tests.
```bash
go test -v ./internal/handler/...
``` …

[Go] Improve DeleteFollowship handler

---

ts/twitter/src/app/(public)/login/_components/account-modal.tsx
ts/twitter/src/app/(public)/login/_components/login-modal.stories.tsx
ts/twitter/src/app/(public)/login/_components/login-modal.tsx
ts/twitter/src/app/(public)/login/_components/password-modal.tsx
ts/twitter/src/app/(public)/signup/_components/signup-modal.tsx

https://github.com/okuda-seminar/Twitter-Clone/issues/758
I added a Link tag to the signup text in the login modal to navigate to /signup. I also modified the UI of the login modal and password modal.
Please verify that:
You can navigate to /signup
There are no differences between the original X and the product UI
Nothing added.
6/20

[TS] Make Signup text clickable to redirect to signup page in login modal

---

ts/twitter/.env.test
ts/twitter/src/__test__/middleware.test.ts
ts/twitter/src/app/(protected)/layout.tsx
ts/twitter/src/app/(public)/layout.tsx
ts/twitter/src/lib/actions/__test__/create-post.test.ts
ts/twitter/src/lib/actions/__test__/find-user-by-id.test.ts
ts/twitter/src/middleware.ts
ts/twitter/vitest.setup.ts

#733 
#763 
Currently, redirect logic is handled in layout.tsx. To improve the architecture for future scalability, I've introduced Next.js middleware. Additionally, this PR resolves issue #763 by implementing proper environment variable mocking in tests.
Currently performing duplicate redirect checks - once in middleware and again in both protected and public layout.tsx files.
- Correctness of middleware test implementation
- Proper middleware integration approach
- Accuracy of middleware behavior
- Correct handling of environment variables in server actions
Run the following commands to verify:
```
npm run test
```
Additionally, temporarily modify layout.tsx to verify middleware is functioning correctly.
Finally, verify that the URL is displayed as follows during action tests:
6/21

[TS] Add middleware to handle redirect decisions

---

go/internal/application/usecase/api/delete_post.go
go/internal/application/usecase/api/delete_repost.go
go/internal/application/usecase/fake/delete_post.go
go/internal/application/usecase/fake/delete_repost.go
go/internal/application/usecase/implementation/delete_post.go
go/internal/application/usecase/implementation/delete_repost.go
go/internal/application/usecase/injector/delete_post.go
go/internal/application/usecase/injector/delete_repost.go
go/internal/controller/handler/delete_post.go
go/internal/controller/handler/delete_post_test.go
go/internal/controller/handler/delete_repost.go
go/internal/controller/handler/delete_repost_test.go
go/internal/controller/handler/errors.go
go/internal/controller/server.go
go/internal/domain/repository/timeline_items.go
go/internal/infrastructure/fake/timeline_items.go
go/internal/infrastructure/implementation/timeline_items.go

#679 
#681 
This PR refactors the `DeletePost` and `DeleteRepost` APIs by moving their core logic from the handler layer to the use case and repository layers.
Since `DeletePostUsecase` and `DeleteRepostUsecase` simply delegate to the repository, dedicated tests for them are not included in this PR.
This refactoring does not change the behavior of the APIs.
Please verify that the APIs can be used properly by following the steps below:
1. Create a post:
```sh
curl --location 'localhost:80/api/users/<your user ID>/posts' \
--header 'Content-Type: application/json' \
--data '{
"text": "test post"
}'
```
2. Create a repost:
```sh
curl --location 'localhost:80/api/users/<your user ID>/reposts' \
--header 'Content-Type: application/json' \
--data '{
"post_id": "<the post ID>"
}'
```
3. Delete …

[Go] Refactor DeletePost and DeleteRepost

---

go/internal/application/usecase/api/errors.go
go/internal/application/usecase/api/like_post.go
go/internal/application/usecase/fake/like_post.go
go/internal/application/usecase/implementation/like_post.go
go/internal/application/usecase/injector/like_post.go
go/internal/controller/handler/errors.go
go/internal/controller/handler/like_post.go
go/internal/controller/handler/like_post_test.go
openapi/paths/users_userId_likes.yml

https://github.com/okuda-seminar/Twitter-Clone/issues/762
This PR introduces a fake implementation of the `LikePost` use case and adds a corresponding suite of unit tests.
The new unit tests validate the behavior of the `LikePost` API endpoint. They can be executed using the go test command.
To ensure compliance with our OpenAPI schema, I've changed the success status code from `w.WriteHeader(http.StatusCreated)` (201) to `w.WriteHeader(http.StatusNoContent) (204)` in the `go/internal/controller/handler/like_post.go`. Please verify this is the correct approach.
This PR coverage is confirmed by:
- Status: 204
- Status: 400
- Status: 500
| Post Already Liked | Post Not Found |
|:---:|:---:|
| <img src="https://github.com/user-attachments/assets/88d6431a-1472-479e-a264-3345e2f …

[Go] Write tests in LikePost

---

go/internal/application/usecase/api/user_by_user_id.go
go/internal/application/usecase/fake/user_by_user_id.go
go/internal/application/usecase/implementation/user_by_user_id.go
go/internal/application/usecase/injector/user_by_user_id.go
go/internal/controller/handler/errors.go
go/internal/controller/handler/find_user_by_id.go
go/internal/controller/handler/find_user_by_id_test.go
go/internal/controller/handler/verify_session.go
go/internal/controller/handler/verify_session_test.go

https://github.com/okuda-seminar/Twitter-Clone/issues/779
This PR introduces a fake implementation of the `UserByUserID` use case and adds a corresponding suite of unit tests.
The new unit tests validate the behavior of the `FindUserByID` API endpoint. They can be executed using the go test command.
By implementing a fake for userByUserID, I also made changes to verify_session_test.go, which was using InjectUserByUserIDUsecase.
7/11

[Go] Write tests in FindUserByID

---

go/internal/application/usecase/api/mute_user.go
go/internal/application/usecase/fake/mute_user.go
go/internal/application/usecase/implementation/mute_user.go
go/internal/application/usecase/injector/mute_user.go
go/internal/controller/handler/errors.go
go/internal/controller/handler/mute_user.go
go/internal/controller/handler/mute_user_test.go

https://github.com/okuda-seminar/Twitter-Clone/issues/795
This PR introduces a fake implementation of the MuteUser use case and adds a corresponding suite of unit tests.
The handler only handles JSON decoding errors (400) and usecase execution errors (500), so I implemented tests for 201 (success) and 500 (error) scenarios only.
The new unit tests validate the behavior of the MuteUser API endpoint. They can be executed using the go test command.
8/1

[Go] Write tests in MuteUser

---

go/internal/application/usecase/api/unlike_post.go
go/internal/application/usecase/fake/unlike_post.go
go/internal/application/usecase/implementation/unlike_post.go
go/internal/application/usecase/injector/unlike_post.go
go/internal/controller/handler/errors.go
go/internal/controller/handler/unlike_post.go
go/internal/controller/handler/unlike_post_test.go

https://github.com/okuda-seminar/Twitter-Clone/issues/790
This PR introduces a fake implementation of the `UnlikePost` use case and adds a corresponding suite of unit tests.
The new unit tests validate the behavior of the `UnlikePost` API endpoint. They can be executed using the go test command.
- Whether the implementation of the fake is correct
- Whether the test cases are sufficient
- Whether the status codes are being checked correctly
`testUnlikePost` checks if the handlers return the expected status code.
08/09

[Go] refactor unlikePost test

---

go/internal/application/usecase/implementation/create_post.go
go/internal/application/usecase/injector/create_post.go
go/internal/controller/handler/create_post_test.go
go/internal/controller/handler/create_quote_repost_test.go
go/internal/controller/handler/get_post_by_post_id_test.go
go/internal/controller/server.go
go/internal/domain/repository/timeline_items.go
go/internal/infrastructure/cache/timeline_items.go
go/internal/infrastructure/fake/timeline_items.go
go/internal/infrastructure/implementation/timeline_items.go
go/internal/infrastructure/rdb/timeline_items.go

#844 
Same with the title
I added an argument, usersID, which is used for `cacheRepository`, to the `CreatePost` method in the `timelineItemsRepository`.
If my modification is acceptable.
I considered introducing an application service and treating the cache and RDB as completely separate repositories. However, since the previous PR was designed both as concrete classes of the timelineItemsRepository, I chose to increase the number of arguments passed to the `CreatePost` method in the `timelineItemsRepository`.
I manually tested the following items.
- When a post is posted, the postID is reflected in the user's timeline in the cache.
I added the following code after the pipelined insertion to Redis
```go
_, err := c.client.Pipelined(ctx, func(p redis.Pipeliner) error {
for _, userID := …
```

[Go] Reflect createPost in cache
